@baseUrl = https://adb-2620936039785376.16.azuredatabricks.net/api/2.0
@token = Bearer 

###
GET {{baseUrl}}/clusters/list
Authorization: {{token}}

###
GET {{baseUrl}}/clusters/get?cluster_id=0817-085257-mire410
Authorization: {{token}}

###
GET {{baseUrl}}/libraries/cluster-status?cluster_id=0817-085257-mire410
Authorization: {{token}}


POST {databricks_instance_extremadura}/api/2.0/libraries/install HTTP/1.1
Content-Type: application/json
{ 
    "Aquí van tus headers": "headers_extremadura", 
    "Y otro header si existe": "Otro valor"
}

{
    "cluster_id": "{new_cluster_id}",
    "libraries": [
        {
            "pypi": {
                "package": "azure-storage-blob==12.3.1"
            }
        }
    ]
}