version: '4.28'

networks:
  presto-network:
    driver: bridge

services:
  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - 9090:9090  # server address
      - 8443:9091  # console address
    volumes:
      - minio-data:/data  # Datos de MinIO
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address ":9090" --console-address ":9091" /data
    networks:
      - presto-network

  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan  # Directorio local de notebooks en el host
    networks:
      - presto-network

volumes:
  minio-data:
