services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis-db
    restart: always
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: python-app
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data: